repositories:
  remote:
    - https://repo.maven.apache.org/maven2
    - https://stocksoftware.jfrog.io/stocksoftware/maven2
    - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  javax_javaee: javax:javaee-api:jar:8.0

  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  # Test deps
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4

  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:4.1.1.164
  javax_json: org.glassfish:javax.json:jar:1.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  testng: org.testng:testng:jar:6.11

  arez_core: org.realityforge.arez:arez-core:jar:0.200
  arez_processor: org.realityforge.arez:arez-processor:jar:0.200

  arez_testng: org.realityforge.arez:arez-extras-testng:jar:0.200

  react4j_core: org.realityforge.react4j:react4j-core:jar:0.183
  react4j_processor: org.realityforge.react4j:react4j-processor:jar:0.183

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-gwt:jar:0.28

  braincheck_core: org.realityforge.braincheck:braincheck-core:jar:1.31.0
  braincheck_jre: org.realityforge.braincheck:braincheck-jre:jar:1.31.0
  braincheck_testng: org.realityforge.braincheck:braincheck-testng:jar:1.31.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.05
  grim_processor: org.realityforge.grim:grim-processor:jar:0.05

  zemeckis: org.realityforge.zemeckis:zemeckis-core:jar:0.13

  gwt_keycloak: org.realityforge.gwt.keycloak:gwt-keycloak:jar:0.7

  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.10.19

  keycloak_core: org.keycloak:keycloak-core:jar:2.0.0.Final
  keycloak_common: org.keycloak:keycloak-common:jar:2.0.0.Final
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:2.0.0.Final
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:2.0.0.Final

  simple_keycloak_service: org.realityforge.keycloak.sks:simple-keycloak-service:jar:0.1

  graphql_java: com.graphql-java:graphql-java:jar:13.0
