load("//third_party/java:rules.bzl", "java_server_library", "java_testng")

java_server_library(
    name = "server_test_support_lib",
    srcs = [
        "EntityChangeCandidateTestUtil.java",
        "ValueUtil.java",
        "package-info.java",
    ],
    visibility = ["//server:__pkg__"],
    deps = [
        "//server/src/main/java/replicant/server:server_core_lib",
        "//third_party/java:testng",
    ],
)

java_testng(
    name = "ChangeSetTest",
    srcs = ["ChangeSetTest.java"],
    test_class = "replicant.server.ChangeSetTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "DatasetAddressTest",
    srcs = ["DatasetAddressTest.java"],
    test_class = "replicant.server.DatasetAddressTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "EntityChangeTest",
    srcs = ["EntityChangeTest.java"],
    test_class = "replicant.server.EntityChangeTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "EntityChangeCandidateSetTest",
    srcs = ["EntityChangeCandidateSetTest.java"],
    test_class = "replicant.server.EntityChangeCandidateSetTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "EntityChangeCandidateSorterTest",
    srcs = ["EntityChangeCandidateSorterTest.java"],
    test_class = "replicant.server.EntityChangeCandidateSorterTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "EntityChangeCandidateTest",
    srcs = ["EntityChangeCandidateTest.java"],
    test_class = "replicant.server.EntityChangeCandidateTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "FilterParameterUtilTest",
    srcs = ["FilterParameterUtilTest.java"],
    test_class = "replicant.server.FilterParameterUtilTest",
    deps = ["//server:server_test_support"],
)

java_testng(
    name = "SubscriptionDependencyCandidateTest",
    srcs = ["SubscriptionDependencyCandidateTest.java"],
    test_class = "replicant.server.SubscriptionDependencyCandidateTest",
    deps = ["//server:server_test_support"],
)
